[package]
name = "rust-scheduler"
version = "0.1.0"
authors = ["Jonathan Beltran <jbelt021@fiu.edu>", "Kennet Postigo <kennetfpostigo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "1.4.1"
async-std = { version = "1.6.0", features = ["attributes"] }
async-trait = "0.1.38"
async-rwlock = "1.0.1"
futures = "0.3.5"
http-types = "2.0.0"
serde = "1.0.115"
serde_json = "1.0.57"
serde_urlencoded = "0.6.1"
surf = "2.0.0-alpha.4"
tide = "0.13.0"
chrono = "0.4.15"

[dev-dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
femme = "1.1.0"
serde = { version = "1.0.115", features = ["derive"] }
mockito = "0.23.3"
