[package]
name = "rust-scheduler"
version = "0.1.0"
authors = ["Jonathan Beltran <jbelt021@fiu.edu>", "Kennet Postigo <kennetfpostigo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
tide = "0.13.0"