version: '3.7'
services: 
  pg: 
    image: postgres:12.4 
    ports: 
      - "5432:5432" 
    volumes: 
      - ./pg:/docker-entrypoint-initdb.d/ 
    environment: 
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test